NO_DEVICE_TEXT = "No device"

PITCH_MAX = 8191

MIDI_MAX_VALUE = 127

MIDI_CC_NAMES: dict[int, str] = {
    0: "Bank Select (MSB)",
    1: "Modulation Wheel (MSB)",
    2: "Breath Controller (MSB)",
    3: "Undefined",
    4: "Foot Controller (MSB)",
    5: "Portamento Time (MSB)",
    6: "Data Entry (MSB)",
    7: "Channel Volume (MSB)",
    8: "Balance (MSB)",
    9: "Undefined",
    10: "Pan (MSB)",
    11: "Expression (MSB)",
    12: "Effect Control 1 (MSB)",
    13: "Effect Control 2 (MSB)",
    14: "Undefined",
    15: "Undefined",
    16: "General Purpose 1 (MSB)",
    17: "General Purpose 2 (MSB)",
    18: "General Purpose 3 (MSB)",
    19: "General Purpose 4 (MSB)",
    20: "Undefined",
    21: "Undefined",
    22: "Undefined",
    23: "Undefined",
    24: "Undefined",
    25: "Undefined",
    26: "Undefined",
    27: "Undefined",
    28: "Undefined",
    29: "Undefined",
    30: "Undefined",
    31: "Undefined",
    32: "Bank Select (LSB)",
    33: "Modulation Wheel (LSB)",
    34: "Breath Controller (LSB)",
    35: "Undefined (LSB)",
    36: "Foot Controller (LSB)",
    37: "Portamento Time (LSB)",
    38: "Data Entry (LSB)",
    39: "Channel Volume (LSB)",
    40: "Balance (LSB)",
    41: "Undefined (LSB)",
    42: "Pan (LSB)",
    43: "Expression (LSB)",
    44: "Effect Control 1 (LSB)",
    45: "Effect Control 2 (LSB)",
    46: "Undefined (LSB)",
    47: "Undefined (LSB)",
    48: "General Purpose 1 (LSB)",
    49: "General Purpose 2 (LSB)",
    50: "General Purpose 3 (LSB)",
    51: "General Purpose 4 (LSB)",
    52: "Undefined (LSB)",
    53: "Undefined (LSB)",
    54: "Undefined (LSB)",
    55: "Undefined (LSB)",
    56: "Undefined (LSB)",
    57: "Undefined (LSB)",
    58: "Undefined (LSB)",
    59: "Undefined (LSB)",
    60: "Undefined (LSB)",
    61: "Undefined (LSB)",
    62: "Undefined (LSB)",
    63: "Undefined (LSB)",
    64: "Damper Pedal (Sustain)",
    65: "Portamento On/Off",
    66: "Sostenuto",
    67: "Soft Pedal",
    68: "Legato Footswitch",
    69: "Hold 2",
    70: "Sound Controller 1 (Sound Variation)",
    71: "Sound Controller 2 (Timbre/Resonance)",
    72: "Sound Controller 3 (Release Time)",
    73: "Sound Controller 4 (Attack Time)",
    74: "Sound Controller 5 (Brightness/Cutoff)",
    75: "Sound Controller 6",
    76: "Sound Controller 7",
    77: "Sound Controller 8",
    78: "Sound Controller 9",
    79: "Sound Controller 10",
    80: "General Purpose 5",
    81: "General Purpose 6",
    82: "General Purpose 7",
    83: "General Purpose 8",
    84: "Portamento Control",
    85: "Undefined",
    86: "Undefined",
    87: "Undefined",
    88: "High Resolution Velocity Prefix",
    89: "Undefined",
    90: "Undefined",
    91: "Effects 1 Depth (Reverb)",
    92: "Effects 2 Depth (Tremolo)",
    93: "Effects 3 Depth (Chorus)",
    94: "Effects 4 Depth (Detune/Celeste)",
    95: "Effects 5 Depth (Phaser)",
    96: "Data Increment",
    97: "Data Decrement",
    98: "NRPN (LSB)",
    99: "NRPN (MSB)",
    100: "RPN (LSB)",
    101: "RPN (MSB)",
    102: "Undefined",
    103: "Undefined",
    104: "Undefined",
    105: "Undefined",
    106: "Undefined",
    107: "Undefined",
    108: "Undefined",
    109: "Undefined",
    110: "Undefined",
    111: "Undefined",
    112: "Undefined",
    113: "Undefined",
    114: "Undefined",
    115: "Undefined",
    116: "Undefined",
    117: "Undefined",
    118: "Undefined",
    119: "Undefined",
    120: "All Sound Off",
    121: "Reset All Controllers",
    122: "Local Control On/Off",
    123: "All Notes Off",
    124: "Omni Mode Off",
    125: "Omni Mode On",
    126: "Mono Mode On (Poly Off)",
    127: "Poly Mode On (Mono Off)",
}

MIDI_NOTE_DETAILS = {
    # Octave -1
    0: {"name": "C", "octave": -1},
    1: {"name": "C♯", "octave": -1},
    2: {"name": "D", "octave": -1},
    3: {"name": "D♯", "octave": -1},
    4: {"name": "E", "octave": -1},
    5: {"name": "F", "octave": -1},
    6: {"name": "F♯", "octave": -1},
    7: {"name": "G", "octave": -1},
    8: {"name": "G♯", "octave": -1},
    9: {"name": "A", "octave": -1},
    10: {"name": "A♯", "octave": -1},
    11: {"name": "B", "octave": -1},
    # Octave 0
    12: {"name": "C", "octave": 0},
    13: {"name": "C♯", "octave": 0},
    14: {"name": "D", "octave": 0},
    15: {"name": "D♯", "octave": 0},
    16: {"name": "E", "octave": 0},
    17: {"name": "F", "octave": 0},
    18: {"name": "F♯", "octave": 0},
    19: {"name": "G", "octave": 0},
    20: {"name": "G♯", "octave": 0},
    21: {"name": "A", "octave": 0},
    22: {"name": "A♯", "octave": 0},
    23: {"name": "B", "octave": 0},
    # Octave 1
    24: {"name": "C", "octave": 1},
    25: {"name": "C♯", "octave": 1},
    26: {"name": "D", "octave": 1},
    27: {"name": "D♯", "octave": 1},
    28: {"name": "E", "octave": 1},
    29: {"name": "F", "octave": 1},
    30: {"name": "F♯", "octave": 1},
    31: {"name": "G", "octave": 1},
    32: {"name": "G♯", "octave": 1},
    33: {"name": "A", "octave": 1},
    34: {"name": "A♯", "octave": 1},
    35: {"name": "B", "octave": 1},
    # Octave 2
    36: {"name": "C", "octave": 2},
    37: {"name": "C♯", "octave": 2},
    38: {"name": "D", "octave": 2},
    39: {"name": "D♯", "octave": 2},
    40: {"name": "E", "octave": 2},
    41: {"name": "F", "octave": 2},
    42: {"name": "F♯", "octave": 2},
    43: {"name": "G", "octave": 2},
    44: {"name": "G♯", "octave": 2},
    45: {"name": "A", "octave": 2},
    46: {"name": "A♯", "octave": 2},
    47: {"name": "B", "octave": 2},
    # Octave 3
    48: {"name": "C", "octave": 3},
    49: {"name": "C♯", "octave": 3},
    50: {"name": "D", "octave": 3},
    51: {"name": "D♯", "octave": 3},
    52: {"name": "E", "octave": 3},
    53: {"name": "F", "octave": 3},
    54: {"name": "F♯", "octave": 3},
    55: {"name": "G", "octave": 3},
    56: {"name": "G♯", "octave": 3},
    57: {"name": "A", "octave": 3},
    58: {"name": "A♯", "octave": 3},
    59: {"name": "B", "octave": 3},
    # Octave 4
    60: {"name": "C", "octave": 4},
    61: {"name": "C♯", "octave": 4},
    62: {"name": "D", "octave": 4},
    63: {"name": "D♯", "octave": 4},
    64: {"name": "E", "octave": 4},
    65: {"name": "F", "octave": 4},
    66: {"name": "F♯", "octave": 4},
    67: {"name": "G", "octave": 4},
    68: {"name": "G♯", "octave": 4},
    69: {"name": "A", "octave": 4},
    70: {"name": "A♯", "octave": 4},
    71: {"name": "B", "octave": 4},
    # Octave 5
    72: {"name": "C", "octave": 5},
    73: {"name": "C♯", "octave": 5},
    74: {"name": "D", "octave": 5},
    75: {"name": "D♯", "octave": 5},
    76: {"name": "E", "octave": 5},
    77: {"name": "F", "octave": 5},
    78: {"name": "F♯", "octave": 5},
    79: {"name": "G", "octave": 5},
    80: {"name": "G♯", "octave": 5},
    81: {"name": "A", "octave": 5},
    82: {"name": "A♯", "octave": 5},
    83: {"name": "B", "octave": 5},
    # Octave 6
    84: {"name": "C", "octave": 6},
    85: {"name": "C♯", "octave": 6},
    86: {"name": "D", "octave": 6},
    87: {"name": "D♯", "octave": 6},
    88: {"name": "E", "octave": 6},
    89: {"name": "F", "octave": 6},
    90: {"name": "F♯", "octave": 6},
    91: {"name": "G", "octave": 6},
    92: {"name": "G♯", "octave": 6},
    93: {"name": "A", "octave": 6},
    94: {"name": "A♯", "octave": 6},
    95: {"name": "B", "octave": 6},
    # Octave 7
    96: {"name": "C", "octave": 7},
    97: {"name": "C♯", "octave": 7},
    98: {"name": "D", "octave": 7},
    99: {"name": "D♯", "octave": 7},
    100: {"name": "E", "octave": 7},
    101: {"name": "F", "octave": 7},
    102: {"name": "F♯", "octave": 7},
    103: {"name": "G", "octave": 7},
    104: {"name": "G♯", "octave": 7},
    105: {"name": "A", "octave": 7},
    106: {"name": "A♯", "octave": 7},
    107: {"name": "B", "octave": 7},
    # Octave 8
    108: {"name": "C", "octave": 8},
    109: {"name": "C♯", "octave": 8},
    110: {"name": "D", "octave": 8},
    111: {"name": "D♯", "octave": 8},
    112: {"name": "E", "octave": 8},
    113: {"name": "F", "octave": 8},
    114: {"name": "F♯", "octave": 8},
    115: {"name": "G", "octave": 8},
    116: {"name": "G♯", "octave": 8},
    117: {"name": "A", "octave": 8},
    118: {"name": "A♯", "octave": 8},
    119: {"name": "B", "octave": 8},
    # Octave 9
    120: {"name": "C", "octave": 9},
    121: {"name": "C♯", "octave": 9},
    122: {"name": "D", "octave": 9},
    123: {"name": "D♯", "octave": 9},
    124: {"name": "E", "octave": 9},
    125: {"name": "F", "octave": 9},
    126: {"name": "F♯", "octave": 9},
    127: {"name": "G", "octave": 9},
}
